# MultiEconomy

# Example of creating a new economy:

# If I wanted to create a new economy called coins, I would do the following...
# I would add the word coins to the economy-types list below
# Then you would create something like this....

# coins:
#   name: Coins
#   symbol: YourSymbolHere
#   start_amount: 100

# If you don't follow the example above you have a good chance of breaking the plugin.

economy-types:
- "gems"
- "tokens"
- "crystals"


gems:
  name: "Gems"
  symbol: "$"
  start_amount: 100

tokens:
  name: "Tokens"
  symbol: "€"
  start_amount: 25

crystals:
  name: "Crystals"
  symbol: "฿"
  start_amount: 50

plugin-prefix: "[&6Multi&eEconomy&f]"

messages:
  help:
  - "&6M&eE &8» &7Usage: /mebalance <player> <economy>"
  - "&6M&eE &8» &7Usage: /mebalances <player>"
  - "&6M&eE &8» &7Usage: /meset <player> <economy> <amount>"
  - "&6M&eE &8» &7Usage: /mereset <player> <economy>"
  - "&6M&eE &8» &7Usage: /megive <player> <economy> <amount>"
  - "&6M&eE &8» &7Usage: /metake <player> <economy> <amount>"
  - "&6M&eE &8» &7Usage: /melist"
  - "&6M&eE &8» &7Usage: /mepay <player> <economy> <amount>"
  commands:
    mebalance:
      invalid-args: "&6M&eE &8» &7Usage: /mebalance <player> <economy>"
      result: "&6M&eE &8» &e{user} &fhas &e{amount} &fof &e{economy}"
    mebalances:
      invalid-args: "&6M&eE &8» &7Usage: /mebalances <player>"
      result: "&6M&eE &8» &e{user} has the following amount of each currency: {currencies}"
    meset:
      invalid-args: "&6M&eE &8» &7Usage: /meset <player> <economy> <amount>"
      result: "&6M&eE &8» &e{user}'s &fbalance for &e{economy} &fhas been set to &e{amount}"
    mereset:
      invalid-args: "&6M&eE &8» &7Usage: /mereset <player> <economy>"
      result: "&6M&eE &8» &e{user}'s &fbalance for &e{economy} &fhas been reset to &e{amount}"
    megive:
      invalid-args: "&6M&eE &8» &7Usage: /megive <player> <economy> <amount>"
      result: "&6M&eE &8» &e{user}'s &fbalance for &e{economy} &fhas is now &e{amount}"
    metake:
      invalid-args: "&6M&eE &8» &7Usage: /metake <player> <economy> <amount>"
      result: "&6M&eE &8» &e{user}'s &fbalance for &e{economy} &fhas is now &e{amount}"
    melist:
      invalid-args: "&6M&eE &8» &7Usage: /melist"
      result: "&6M&eE &8» &eThe following economy types are available: {currencies}"
    mepay:
      invalid-args: "&6M&eE &8» &7Usage: /mepay <player> <economy> <amount>"
      result: "&6M&eE &8» &eYou have sent &f{amount} of &e{economy} &f to {user}"
  error:
    no-permission: "&6M&eE &8» &cYou do not have permission to run this command!"
    eco-doesnt-exist: "&6M&eE &8» That economy type doesn't exist!"
    player-doesnt-exist: "&6M&eE &8» That player does not exist on this server!"
    data-doesnt-exist: "&6M&eE &8» That user has no data for the economy you checked!"
    eco-player-doesnt-exist: "&6M&eE &8» &cThere is no economy data for this user!"
    not-valid-number: "&6M&eE &8» &cThe input give was not a valid number!"
    player-doesnt-have-enough: "&6M&eE &8» &cThat player doesn't have that many {economy}!"
    not-enough-pay: "&6M&eE &8» &cYou don't have enough {economy}!"