# MultiEconomy

# Example of creating a new economy:

# If I wanted to create a new economy called coins, I would do the following...
# I would add the word coins to the economy-types list below
# Then you would create something like this....

# coins:
#   name: Coins
#   symbol: YourSymbolHere
#   start_amount: 100
#   item: BOOK
#   slot: 3

# If you don't follow the example above you have a good chance of breaking the plugin.

# This is used to determine what version of the config you are using.
# Please do not change this as it may cause issues with your config.
version: 1

# This will automatically move your current config to "config-old.yml" and replace with a new, updated, "config.yml".
# If you ever get tired of your config being moved, just change this to "false".
auto-update-config: true

# Supports YML or MySQL
database:
  type: YML
# Uncomment when using MySQL
#  host: "localhost"
#  port: 3306
#  username: "root"
#  password: "password"
#  database: "multieconomy"
#  pool-size: 10



economy-types:
- "gems"
- "tokens"
- "crystals"


balances-gui:
  title: "{name}'s balances"
  size: 9
  items:
    name: "{economy} - {amount}"

leaderboard-gui:
  title: "Top players for the economy {economy}"
  size: 9
  items:
    name: "{name} » {amount}"


gems:
  name: "Gems"
  symbol: "$"
  start_amount: 100
  item: "EMERALD"
  slot: 0

tokens:
  name: "Tokens"
  symbol: "€"
  start_amount: 25
  item: "GOLD_NUGGET"
  slot: 1

crystals:
  name: "Crystals"
  symbol: "฿"
  start_amount: 50
  item: "DIAMOND"
  slot: 2

plugin-prefix: "[&6Multi&eEconomy&f]"

messages:
  help:
  - "&6M&eE &8» &7Usage: /mebalance <player> <economy>"
  - "&6M&eE &8» &7Usage: /mebalances <player>"
  - "&6M&eE &8» &7Usage: /meset <player> <economy> <amount>"
  - "&6M&eE &8» &7Usage: /mereset <player> <economy>"
  - "&6M&eE &8» &7Usage: /megive <player> <economy> <amount>"
  - "&6M&eE &8» &7Usage: /metake <player> <economy> <amount>"
  - "&6M&eE &8» &7Usage: /melist"
  - "&6M&eE &8» &7Usage: /mepay <player> <economy> <amount>"
  - "&6M&eE &8» &7Usage: /metop <economy>"
  commands:
    mebalance:
      invalid-args: "&6M&eE &8» &7Usage: /mebalance <player> <economy>"
      result: "&6M&eE &8» &e{user} &fhas &e{amount} &fof &e{economy}"
    mebalances:
      invalid-args: "&6M&eE &8» &7Usage: /mebalances <player>"
      result: "&6M&eE &8» &e{user} has the following amount of each currency: {currencies}"
    meset:
      invalid-args: "&6M&eE &8» &7Usage: /meset <player> <economy> <amount>"
      result: "&6M&eE &8» &e{user}'s &fbalance for &e{economy} &fhas been set to &e{amount}"
    mereset:
      invalid-args: "&6M&eE &8» &7Usage: /mereset <player> <economy>"
      result: "&6M&eE &8» &e{user}'s &fbalance for &e{economy} &fhas been reset to &e{amount}"
    megive:
      invalid-args: "&6M&eE &8» &7Usage: /megive <player> <economy> <amount>"
      result: "&6M&eE &8» &e{user}'s &fbalance for &e{economy} &fhas is now &e{amount}"
    metake:
      invalid-args: "&6M&eE &8» &7Usage: /metake <player> <economy> <amount>"
      result: "&6M&eE &8» &e{user}'s &fbalance for &e{economy} &fhas is now &e{amount}"
    melist:
      invalid-args: "&6M&eE &8» &7Usage: /melist"
      result: "&6M&eE &8» &eThe following economy types are available: {currencies}"
    mepay:
      invalid-args: "&6M&eE &8» &7Usage: /mepay <player> <economy> <amount>"
      result: "&6M&eE &8» &eYou have sent &f{amount} of &e{economy} &f to {user}"
    metop:
      invalid-args: "&6M&eE &8» &7Usage: /metop <economy>"
      wait: "&6M&eE &8» &7Generating data... Please wait 1 second!"
  error:
    no-permission: "&6M&eE &8» &cYou do not have permission to run this command!"
    eco-doesnt-exist: "&6M&eE &8» That economy type doesn't exist!"
    player-doesnt-exist: "&6M&eE &8» That player does not exist on this server!"
    data-doesnt-exist: "&6M&eE &8» That user has no data for the economy you checked!"
    eco-player-doesnt-exist: "&6M&eE &8» &cThere is no economy data for this user!"
    not-valid-number: "&6M&eE &8» &cThe input give was not a valid number!"
    player-doesnt-have-enough: "&6M&eE &8» &cThat player doesn't have that many {economy}!"
    not-enough-pay: "&6M&eE &8» &cYou don't have enough {economy}!"