name: MultiEconomy
version: ${project.version}
main: me.glaremasters.multieconomy.MultiEconomy
authors: [blockslayer22]
description: MultiEconomy
website: https://glaremasters.me/discord


permissions:
  me.user:
    description: All permissions for general users
    children:
      me.balance: true
      me.balances: true
      me.help: true
      me.list: true
      me.pay: true
      me.top: true
  me.admin:
    description: All permissions of the plugin
    children:
      me.balance: true
      me.balances: true
      me.help: true
      me.list: true
      me.pay: true
      me.give: true
      me.reset: true
      me.set: true
      me.take: true
      me.version: true
      me.top: true
    default: op

