name: MultiEconomy
version: ${project.version}
main: me.glaremasters.multieconomy.MultiEconomy
authors: [blockslayer22]
description: MultiEconomy
website: https://glaremasters.me/discord

commands:
  mebalance:
    description: mebalance
  meset:
    description: meset
  mereset:
    description: mereset
  megive:
    description: megive
  metake:
    description: metake
  melist:
    description: melist
  mebalances:
    description: mebalances
  mepay:
    description: mepay
  mehelp:
    description: mehelp
  meversion:
    description: meversion
  metop:
    description: metop

permissions:
  me.user:
    description: All permissions for general users
    children:
      me.balance: true
      me.balances: true
      me.help: true
      me.list: true
      me.pay: true
      me.top: true
  me.admin:
    description: All permissions of the plugin
    children:
      me.balance: true
      me.balances: true
      me.help: true
      me.list: true
      me.pay: true
      me.give: true
      me.reset: true
      me.set: true
      me.take: true
      me.version: true
      me.top: true
    default: op

